from __future__ import annotations

import os
from importlib import import_module

if not os.environ.get("LOKY_MAX_CPU_COUNT"):
    os.environ["LOKY_MAX_CPU_COUNT"] = str(os.cpu_count() or 1)

_LAZY_MODULES: dict[str, str] = {
    "factor_algorithm": "tiger_factors.factor_algorithm",
    "factor_evaluation": "tiger_factors.factor_evaluation",
    "factor_frame": "tiger_factors.factor_frame",
    "factor_maker": "tiger_factors.factor_maker",
    "factor_ml": "tiger_factors.factor_ml",
    "factor_allocation": "tiger_factors.factor_allocation",
    "factor_backtest": "tiger_factors.factor_backtest",
    "factor_preprocessing": "tiger_factors.factor_preprocessing",
    "factor_portfolio": "tiger_factors.factor_portfolio",
    "factor_test": "tiger_factors.factor_test",
    "factor_store": "tiger_factors.factor_store",
    "factor_screener": "tiger_factors.factor_screener",
    "multifactor_evaluation": "tiger_factors.multifactor_evaluation",
}

_LAZY_ATTRS: dict[str, tuple[str, str]] = {
    "Alpha101Engine": ("tiger_factors.factor_algorithm.alpha101.engine", "Alpha101Engine"),
    "Alpha158FactorSet": ("tiger_factors.factor_algorithm.qlib_factors.alpha_sets", "Alpha158FactorSet"),
    "Alpha360FactorSet": ("tiger_factors.factor_algorithm.qlib_factors.alpha_sets", "Alpha360FactorSet"),
    "AnnualFinancialFactorEngine": ("tiger_factors.factor_algorithm.financial_factors.financial_factors", "AnnualFinancialFactorEngine"),
    "DataMiningEngine": ("tiger_factors.factor_algorithm.data_mining.factors", "DataMiningEngine"),
    "DataPreprocessingService": ("tiger_factors.factor_ml.data_mining", "DataPreprocessingService"),
    "FactorTimingPipelineEngine": ("tiger_factors.factor_algorithm.factor_timing.pipeline", "FactorTimingPipelineEngine"),
    "FactorTimingPipelineResult": ("tiger_factors.factor_algorithm.factor_timing.pipeline", "FactorTimingPipelineResult"),
    "FactorFrameContext": ("tiger_factors.factor_frame.engine", "FactorFrameContext"),
    "FactorFrameEngine": ("tiger_factors.factor_frame.engine", "FactorFrameEngine"),
    "FactorFrameFeed": ("tiger_factors.factor_frame.engine", "FactorFrameFeed"),
    "FactorFrameResult": ("tiger_factors.factor_frame.engine", "FactorFrameResult"),
    "FinancialFactorEngine": ("tiger_factors.factor_algorithm.financial_factors.financial_factors", "FinancialFactorEngine"),
    "FactorGeneratorService": ("tiger_factors.factor_ml.data_mining", "FactorGeneratorService"),
    "NeutralizationColumns": ("tiger_factors.factor_algorithm.alpha101.engine", "NeutralizationColumns"),
    "GeneticFactorMiningService": ("tiger_factors.factor_ml.data_mining", "GeneticFactorMiningService"),
    "PracticalFactorEngine": ("tiger_factors.factor_algorithm.data_mining.practical_factors.factors", "PracticalFactorEngine"),
    "QlibAlphaFactorSetEngine": ("tiger_factors.factor_algorithm.qlib_factors.alpha_sets", "QlibAlphaFactorSetEngine"),
    "QuarterlyFinancialFactorEngine": ("tiger_factors.factor_algorithm.financial_factors.financial_factors", "QuarterlyFinancialFactorEngine"),
    "StreamingFactorEngine": ("tiger_factors.factor_maker.streaming", "StreamingFactorEngine"),
    "TTMFinancialFactorEngine": ("tiger_factors.factor_algorithm.financial_factors.financial_factors", "TTMFinancialFactorEngine"),
    "TraditionalFactorPipelineEngine": ("tiger_factors.factor_algorithm.traditional_factors.pipeline", "TraditionalFactorPipelineEngine"),
    "TraditionalFactorPipelineResult": ("tiger_factors.factor_algorithm.traditional_factors.pipeline", "TraditionalFactorPipelineResult"),
    "ValuationFactorEngine": ("tiger_factors.factor_algorithm.valuation_factors.valuation_factors", "ValuationFactorEngine"),
    "FactorScreener": ("tiger_factors.factor_screener", "FactorScreener"),
    "FactorScreenerResult": ("tiger_factors.factor_screener", "FactorScreenerResult"),
    "FactorScreenerSpec": ("tiger_factors.factor_screener", "FactorScreenerSpec"),
    "MarginalScreener": ("tiger_factors.factor_screener", "MarginalScreener"),
    "MarginalScreenerResult": ("tiger_factors.factor_screener", "MarginalScreenerResult"),
    "MarginalScreenerSpec": ("tiger_factors.factor_screener", "MarginalScreenerSpec"),
    "BacktestMarginalScreener": ("tiger_factors.factor_screener", "BacktestMarginalScreener"),
    "BacktestMarginalScreenerResult": ("tiger_factors.factor_screener", "BacktestMarginalScreenerResult"),
    "BacktestMarginalScreenerSpec": ("tiger_factors.factor_screener", "BacktestMarginalScreenerSpec"),
    "ReturnAdapter": ("tiger_factors.factor_screener", "ReturnAdapter"),
    "ReturnAdapterResult": ("tiger_factors.factor_screener", "ReturnAdapterResult"),
    "ReturnAdapterSpec": ("tiger_factors.factor_screener", "ReturnAdapterSpec"),
    "ScreenerFinalResult": ("tiger_factors.factor_screener", "ScreenerFinalResult"),
    "Screener": ("tiger_factors.factor_screener", "Screener"),
    "ScreenerResult": ("tiger_factors.factor_screener", "ScreenerResult"),
    "MultifactorAnalysisReportResult": ("tiger_factors.multifactor_evaluation", "MultifactorAnalysisReportResult"),
    "MultifactorAnalysisReportSpec": ("tiger_factors.multifactor_evaluation", "MultifactorAnalysisReportSpec"),
    "create_analysis_report": ("tiger_factors.multifactor_evaluation", "create_analysis_report"),
    "factor_convexity_test": ("tiger_factors.factor_test", "factor_convexity_test"),
    "factor_decay_test": ("tiger_factors.factor_test", "factor_decay_test"),
    "factor_effectiveness_test": ("tiger_factors.factor_test", "factor_effectiveness_test"),
    "factor_recent_ic_test": ("tiger_factors.factor_test", "factor_recent_ic_test"),
    "factor_stability_test": ("tiger_factors.factor_test", "factor_stability_test"),
    "build_market_state_features": ("tiger_factors.factor_test", "build_market_state_features"),
    "build_hmm_market_state_labels": ("tiger_factors.factor_test", "build_hmm_market_state_labels"),
    "build_kmeans_market_state_labels": ("tiger_factors.factor_test", "build_kmeans_market_state_labels"),
    "expand_date_market_state_to_group_labels": ("tiger_factors.factor_test", "expand_date_market_state_to_group_labels"),
    "market_state_test": ("tiger_factors.factor_test", "market_state_test"),
    "factor_regime_ic_test": ("tiger_factors.factor_test", "factor_regime_ic_test"),
    "factor_regime_stability_test": ("tiger_factors.factor_test", "factor_regime_stability_test"),
    "factor_regime_report": ("tiger_factors.factor_test", "factor_regime_report"),
    "build_single_factor_return_long_frame": ("tiger_factors.factor_evaluation.factor_screening", "build_single_factor_return_long_frame"),
    "allocate_from_return_panel": ("tiger_factors.factor_allocation", "allocate_from_return_panel"),
    "FactorPreprocessor": ("tiger_factors.factor_preprocessing", "FactorPreprocessor"),
    "bin_factor_panel": ("tiger_factors.factor_preprocessing", "bin_factor_panel"),
    "coerce_factor_panel": ("tiger_factors.factor_preprocessing", "coerce_factor_panel"),
    "cs_minmax_neg": ("tiger_factors.factor_preprocessing", "cs_minmax_neg"),
    "cs_minmax_pos": ("tiger_factors.factor_preprocessing", "cs_minmax_pos"),
    "cs_neutralize": ("tiger_factors.factor_preprocessing", "cs_neutralize"),
    "cs_rank": ("tiger_factors.factor_preprocessing", "cs_rank"),
    "cs_winsorize": ("tiger_factors.factor_preprocessing", "cs_winsorize"),
    "cs_winsorize_mad": ("tiger_factors.factor_preprocessing", "cs_winsorize_mad"),
    "cs_zscore": ("tiger_factors.factor_preprocessing", "cs_zscore"),
    "demean": ("tiger_factors.factor_preprocessing", "demean"),
    "detect_outliers_factor_panel": ("tiger_factors.factor_preprocessing", "detect_outliers_factor_panel"),
    "fill_missing_factor_panel": ("tiger_factors.factor_preprocessing", "fill_missing_factor_panel"),
    "l1_normalize": ("tiger_factors.factor_preprocessing", "l1_normalize"),
    "l2_normalize": ("tiger_factors.factor_preprocessing", "l2_normalize"),
    "minmax_scale": ("tiger_factors.factor_preprocessing", "minmax_scale"),
    "neutralize_factor_panel": ("tiger_factors.factor_preprocessing", "neutralize_factor_panel"),
    "normalize_cross_section": ("tiger_factors.factor_preprocessing", "normalize_cross_section"),
    "neutralize_cross_section": ("tiger_factors.factor_preprocessing", "neutralize_cross_section"),
    "preprocess_cross_section": ("tiger_factors.factor_preprocessing", "preprocess_cross_section"),
    "preprocess_factor_panel": ("tiger_factors.factor_preprocessing", "preprocess_factor_panel"),
    "rank_centered": ("tiger_factors.factor_preprocessing", "rank_centered"),
    "rank_pct": ("tiger_factors.factor_preprocessing", "rank_pct"),
    "replace_outliers_with_nan": ("tiger_factors.factor_preprocessing", "replace_outliers_with_nan"),
    "robust_zscore": ("tiger_factors.factor_preprocessing", "robust_zscore"),
    "scale_factor_panel": ("tiger_factors.factor_preprocessing", "scale_factor_panel"),
    "winsorize_cross_section": ("tiger_factors.factor_preprocessing", "winsorize_cross_section"),
    "winsorize_mad": ("tiger_factors.factor_preprocessing", "winsorize_mad"),
    "winsorize_quantile": ("tiger_factors.factor_preprocessing", "winsorize_quantile"),
    "target_encode_binned": ("tiger_factors.factor_preprocessing", "target_encode_binned"),
    "woe_encode_binned": ("tiger_factors.factor_preprocessing", "woe_encode_binned"),
    "winsorize_factor_panel": ("tiger_factors.factor_preprocessing", "winsorize_factor_panel"),
    "zscore": ("tiger_factors.factor_preprocessing", "zscore"),
    "factor_to_stock_portfolio": ("tiger_factors.factor_portfolio", "factor_to_stock_portfolio"),
    "multi_factor_to_stock_portfolio": ("tiger_factors.factor_portfolio", "multi_factor_to_stock_portfolio"),
    "summarize_factor_portfolio_holdings": ("tiger_factors.factor_portfolio", "summarize_factor_portfolio_holdings"),
    "run_factor_portfolio_workflow": ("tiger_factors.factor_portfolio", "run_factor_portfolio_workflow"),
    "run_weight_panel_backtest": ("tiger_factors.factor_portfolio", "run_weight_panel_backtest"),
    "run_factor_screener": ("tiger_factors.factor_screener", "run_factor_screener"),
    "run_factor_screener_batch": ("tiger_factors.factor_screener", "run_factor_screener_batch"),
    "run_screener": ("tiger_factors.factor_screener", "run_screener"),
    "run_return_backtest": ("tiger_factors.factor_backtest", "run_return_backtest"),
    "alpha101_descriptions": ("tiger_factors.factor_algorithm.alpha101.descriptions", "alpha101_descriptions"),
    "alpha101_factor_names": ("tiger_factors.factor_algorithm.alpha101.engine", "alpha101_factor_names"),
    "alpha158_feature_config": ("tiger_factors.factor_algorithm.qlib_factors.alpha_sets", "alpha158_feature_config"),
    "alpha360_feature_config": ("tiger_factors.factor_algorithm.qlib_factors.alpha_sets", "alpha360_feature_config"),
    "available_qlib_factor_sets": ("tiger_factors.factor_algorithm.qlib_factors.alpha_sets", "available_qlib_factor_sets"),
    "available_traditional_factor_names": ("tiger_factors.factor_algorithm.traditional_factors.pipeline", "available_traditional_factor_names"),
    "data_mining_factor_names": ("tiger_factors.factor_algorithm.data_mining.factors", "available_factors"),
    "practical_factor_names": ("tiger_factors.factor_algorithm.data_mining.practical_factors.factors", "available_practical_factors"),
}

__all__ = [
    "factor_algorithm",
    "factor_evaluation",
    "factor_frame",
    "factor_maker",
    "factor_ml",
    "factor_allocation",
    "factor_backtest",
    "factor_portfolio",
    "factor_test",
    "factor_preprocessing",
    "factor_store",
    "factor_screener",
    "multifactor_evaluation",
    "Alpha101Engine",
    "NeutralizationColumns",
    "alpha101_descriptions",
    "alpha101_factor_names",
    "DataMiningEngine",
    "data_mining_factor_names",
    "DataPreprocessingService",
    "FactorFrameContext",
    "FactorFrameEngine",
    "FactorFrameFeed",
    "FactorFrameResult",
    "FactorTimingPipelineEngine",
    "FactorGeneratorService",
    "PracticalFactorEngine",
    "GeneticFactorMiningService",
    "practical_factor_names",
    "StreamingFactorEngine",
    "TraditionalFactorPipelineEngine",
    "FactorScreener",
    "FactorScreenerResult",
    "FactorScreenerSpec",
    "MarginalScreener",
    "MarginalScreenerResult",
    "MarginalScreenerSpec",
    "BacktestMarginalScreener",
    "BacktestMarginalScreenerResult",
    "BacktestMarginalScreenerSpec",
    "ReturnAdapter",
    "ReturnAdapterResult",
    "ReturnAdapterSpec",
    "ScreenerFinalResult",
    "Screener",
    "ScreenerResult",
    "MultifactorAnalysisReportResult",
    "MultifactorAnalysisReportSpec",
    "create_analysis_report",
    "factor_convexity_test",
    "factor_decay_test",
    "factor_effectiveness_test",
    "factor_recent_ic_test",
    "factor_stability_test",
    "build_market_state_features",
    "build_hmm_market_state_labels",
    "build_kmeans_market_state_labels",
    "expand_date_market_state_to_group_labels",
    "market_state_test",
    "factor_regime_ic_test",
    "factor_regime_stability_test",
    "factor_regime_report",
    "FactorPreprocessor",
    "bin_factor_panel",
    "coerce_factor_panel",
    "cs_minmax_neg",
    "cs_minmax_pos",
    "cs_neutralize",
    "cs_rank",
    "cs_winsorize",
    "cs_winsorize_mad",
    "cs_zscore",
    "demean",
    "detect_outliers_factor_panel",
    "fill_missing_factor_panel",
    "l1_normalize",
    "l2_normalize",
    "minmax_scale",
    "neutralize_factor_panel",
    "normalize_cross_section",
    "neutralize_cross_section",
    "preprocess_cross_section",
    "preprocess_factor_panel",
    "rank_centered",
    "rank_pct",
    "replace_outliers_with_nan",
    "robust_zscore",
    "scale_factor_panel",
    "winsorize_cross_section",
    "winsorize_mad",
    "winsorize_quantile",
    "target_encode_binned",
    "woe_encode_binned",
    "winsorize_factor_panel",
    "zscore",
    "run_factor_screener",
    "run_factor_screener_batch",
    "run_screener",
    "build_single_factor_return_long_frame",
    "allocate_from_return_panel",
    "factor_to_stock_portfolio",
    "multi_factor_to_stock_portfolio",
    "summarize_factor_portfolio_holdings",
    "run_factor_portfolio_workflow",
    "run_weight_panel_backtest",
    "run_return_backtest",
]


def __getattr__(name: str):
    module_path = _LAZY_MODULES.get(name)
    if module_path is not None:
        module = import_module(module_path)
        globals()[name] = module
        return module

    target = _LAZY_ATTRS.get(name)
    if target is not None:
        module = import_module(target[0])
        value = getattr(module, target[1])
        globals()[name] = value
        return value

    raise AttributeError(f"module 'tiger_factors' has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__) | set(_LAZY_MODULES) | set(_LAZY_ATTRS))
