from __future__ import annotations

"""
Alpha101 factor summaries.

These short descriptions are inferred from the formulas in
`tiger_factors.factor_algorithm.alpha101.engine`. They are intentionally concise and are meant
to explain what each alpha is trying to measure at a glance.
"""

ALPHA101_DESCRIPTIONS: dict[int, str] = {
    1: "5-day extreme in 20-day return volatility triggers reversal",
    2: "6-day negative correlation between volume change and intraday return",
    3: "10-day negative correlation between open price and volume",
    4: "9-day time-series weakness in low-price cross-sectional rank",
    5: "Contrarian mix of open-VWAP and close-VWAP deviations",
    6: "10-day negative correlation between open price and volume",
    7: "7-day price momentum switches by a 20-day average-volume threshold",
    8: "10-day reversal from the product of 5-day open and return",
    9: "5-day regime-switch signal on 1-day price changes",
    10: "Ranked regime-switch signal on 1-day changes over 4 days",
    11: "Composite signal from VWAP deviation extremes and volume change",
    12: "Reversal signal from volume-change direction times price-change direction",
    13: "Inverse rank of 5-day covariance between close and volume",
    14: "Inverse signal from 3-day return changes and open-volume correlation",
    15: "3-day aggregated inverse signal from high-price and volume correlation",
    16: "Inverse rank of 5-day covariance between high price and volume",
    17: "Composite of trend, acceleration, and relative volume strength",
    18: "Inverse composite of price volatility, intraday range, and open-close correlation",
    19: "7-day price-change trend plus 250-day return rank",
    20: "Triple reversal signal from open-high-low deviations",
    21: "Conditional regime signal from 8/2-day moving-average divergence and volume strength",
    22: "Blend of high-price volume-related change rate and price volatility",
    23: "Accelerated pullback signal for highs within a 20-day high range",
    24: "100-day mean-price deviation and 100-day momentum pullback signal",
    25: "Cross-sectional rank of return, volume, VWAP, and high-close spread",
    26: "3-day peak reversal in volume-high correlation",
    27: "Layered reversal signal from 6-day price-volume correlation",
    28: "Scaled neutral signal from ADV20 and low-price correlation",
    29: "5-day momentum and 6-day inverse return layered on multi-level ranks",
    30: "Price-direction consistency over 3 days with 5/20-day volume ratio",
    31: "10-day momentum decay, 3-day reversal, and low-price correlation",
    32: "7-day mean-price deviation plus 230-day VWAP correlation",
    33: "Reversal rank of the open/close ratio",
    34: "Combined short-term return-volatility ratio and price-direction signal",
    35: "32-day time-series strength of volume-price combination",
    36: "Composite score from open-close, returns, and VWAP-ADV correlations",
    37: "200-day correlation plus deviation of prior open-close and current close",
    38: "Combined reversal of close strength and open-close ratio",
    39: "7-day price-change signal with volume decay strength and 250-day return rank",
    40: "Inverse signal from high-price volatility and high-price volume correlation",
    41: "Geometric mean of the typical price spread minus VWAP",
    42: "Normalized cross-sectional rank of VWAP minus close",
    43: "Double time-series rank of volume relative to ADV20 and 7-day price change",
    44: "Inverse 5-day correlation between high price and volume rank",
    45: "Composite reversal from 20-day lagged close mean, 2-day volume correlation, and 5/20-day close correlation",
    46: "Conditional reversal under divergence between 20-day and 10-day price slopes",
    47: "Weighted combination of price, volume, VWAP change, and high-low spread",
    48: "Neutralized return ratio from correlation between price changes and lagged price changes",
    49: "Conditional reversal under 20-day vs 10-day price slope divergence",
    50: "5-day peak reversal in volume-VWAP correlation",
    51: "Threshold reversal variant of 20-day and 10-day trend divergence",
    52: "Composite signal from low-price extremes, long-term return trend, and short-term volume rank",
    53: "Inverse 9-day change in high-low spread structure",
    54: "Extreme leverage signal from low-high spread and open-price to the fifth power",
    55: "Inverse signal from 12-day price-range strength and volume correlation",
    56: "Inverse combination of 10-day return and market-value-weighted return",
    57: "Close-VWAP deviation divided by decaying 30-day high-price extrema",
    58: "Decayed reversal of sector-neutral VWAP-volume correlation",
    59: "Decayed reversal of industry-neutral VWAP-volume correlation",
    60: "Negative coupling between price-range strength and ADV20 strength",
    61: "Threshold signal on VWAP new highs versus 180-day ADV correlation",
    62: "Threshold signal from VWAP/22-day ADV correlation and open-high-low structure",
    63: "Decayed difference between industry-neutral close change and long-horizon ADV correlation",
    64: "Threshold signal from weighted open-low correlation and 120-day ADV",
    65: "Comparison of open-VWAP correlation and open-low strength",
    66: "Inverse composite of decayed VWAP change and low-price-VWAP deviation",
    67: "Power transform of high-low range strength and neutral liquidity correlation",
    68: "Time-series rank of high-price strength vs short-term price change through 15-day ADV correlation",
    69: "Power signal from industry-neutral VWAP high-point change and price/VWAP mix relative to 20-day ADV",
    70: "Power reversal from daily VWAP change and industry-neutral close-ADV50 correlation",
    71: "Composite signal from ranked price momentum, ADV180 correlation, and squared low-point deviation",
    72: "Decayed signal of median-price and ADV40 correlation divided by decayed VWAP-volume correlation",
    73: "Time-series reversal from decayed VWAP change and weighted open-low change rate",
    74: "Close versus long-term ADV correlation compared with high-price-VWAP correlation",
    75: "Binary comparison of VWAP-volume correlation and low-ADV50 correlation",
    76: "Composite reversal from VWAP change and sector-neutral low-ADV81 correlation",
    77: "Double-decay minimum of median-price-VWAP deviation and median-price-ADV40 correlation",
    78: "Power combination of long-term low-price-VWAP liquidity correlation and VWAP-volume correlation",
    79: "Comparison of industry-neutral close-open change and VWAP-ADV150 correlation",
    80: "Negative power signal from industry-neutral open-high change direction and high-ADV10 correlation",
    81: "Threshold product of VWAP-ADV10 correlation and VWAP-volume correlation",
    82: "Composite reversal from decayed open-change and sector-neutral volume-open correlation",
    83: "Joint signal from range strength, volume rank, and spread ratio",
    84: "Time-series strength of VWAP relative to the 15-day high plus 5-day price change",
    85: "Power combination of high-price close weighting, ADV30 correlation, and high-low mean-volume correlation",
    86: "Inverse decision when close-ADV20 correlation is weaker than close-VWAP deviation",
    87: "Double-decay reversal of industry-neutral ADV81 and close correlation",
    88: "Composite of cross-sectional open-high-low-close spread decay and close/ADV60 correlation",
    89: "Difference between low-price-ADV10 correlation and decayed industry-neutral VWAP change",
    90: "Power reversal from deviation from the 5-day high and subindustry-neutral low correlation",
    91: "Double-decay industry-neutral close-volume correlation versus VWAP-ADV30 comparison",
    92: "Decayed rank of high-low-mid-close inequality conditions and low-ADV30 correlation rank",
    93: "Decayed industry-neutral VWAP-ADV81 correlation versus price-mix change comparison",
    94: "Power reversal from VWAP relative to the 12-day low and VWAP/ADV60 correlation",
    95: "Threshold signal from open relative to the 12-day low and median-price-ADV40 correlation",
    96: "Extreme reversal from decayed VWAP-volume correlation and close/ADV60 correlation",
    97: "Decayed reversal from industry-neutral low-price-VWAP mixed change and low-ADV60 correlation",
    98: "Minimum of decayed VWAP-ADV5 correlation versus open/ADV15 correlation",
    99: "Comparison of high-low mean and ADV60 correlation versus low-price-volume correlation",
    100: "Composite penalty from price-volume imbalance and subindustry-neutral residual structure",
    101: "Intraday body-to-range strength signal",
}


def alpha101_description(alpha_id: int) -> str:
    return ALPHA101_DESCRIPTIONS[alpha_id]


def alpha101_descriptions() -> dict[int, str]:
    return dict(ALPHA101_DESCRIPTIONS)
