from __future__ import annotations

from tiger_factors.utils.cross_sectional import (
    bucketize_quantiles,
    col_minmax_neg,
    col_minmax_pos,
    group_demean,
    group_dummy_regression_residual,
    group_zscore as cs_group_zscore,
    industry_regression_residual,
    industry_size_regression_residual,
    make_industry_dummies,
    make_onehot_by_group,
    neutralize_by_group,
    neutralize_industry_size,
    orthogonalize,
)
from tiger_factors.utils.group_operators import (
    combo_a,
    group_backfill,
    group_cartesian_product,
    group_max,
    group_mean,
    group_min,
    group_neutralize,
    group_rank,
    group_scale,
    group_zscore,
)
from tiger_factors.utils.time_series import (
    cumulative_return,
    decay_exponential,
    decay_linear,
    diff,
    drawdown,
    ewm_mean,
    ewm_std,
    expanding_zscore,
    lag,
    log_return,
    max_drawdown,
    pct_change,
    rolling_beta,
    rolling_corr,
    ts_arg_max,
    ts_arg_min,
    ts_av_diff,
    ts_backfill,
    ts_corr,
    ts_covariance,
    ts_delay,
    ts_delta,
    ts_max,
    ts_mean,
    ts_min,
    rolling_information_ratio,
    rolling_kurt,
    rolling_max,
    rolling_mean,
    rolling_median,
    rolling_min,
    ts_product,
    ts_quantile,
    ts_rank,
    rolling_rank_pct,
    rolling_sharpe,
    rolling_skew,
    rolling_std,
    rolling_sum,
    rolling_zscore,
    ts_scale,
    ts_std_dev,
    ts_sum,
    ts_ema,
    ts_pctchange,
    ts_var,
    ts_momentum,
    ts_wma,
    ts_winsorize,
    ts_winsorize_mad,
    ts_zscore,
    volatility,
)
from tiger_factors.utils.combine import (
    blend_factor_panels,
    cross_sectional_zscore,
    factor_correlation_matrix,
    greedy_select_by_correlation,
)
from tiger_factors.utils.asof_align import align_fundamental_point_in_time
from tiger_factors.utils.panel_ops import (
    cs_rank as panel_cs_rank,
    cs_regression_residual as panel_cs_regression_residual,
    cs_skew as panel_cs_skew,
    cs_standardize as panel_cs_standardize,
    delay as panel_delay,
    rolling_max_drawdown as panel_rolling_max_drawdown,
    rolling_sharpe as panel_rolling_sharpe,
    rolling_volatility as panel_rolling_volatility,
    signed_power as panel_signed_power,
    ts_av_diff as panel_ts_av_diff,
    ts_corr as panel_ts_corr,
    ts_cov as panel_ts_cov,
    ts_decay_linear as panel_ts_decay_linear,
    ts_delta as panel_ts_delta,
    ts_ema as panel_ts_ema,
    ts_ir as panel_ts_ir,
    ts_mean as panel_ts_mean,
    ts_median as panel_ts_median,
    ts_max as panel_ts_max,
    ts_min as panel_ts_min,
    ts_pctchange as panel_ts_pctchange,
    ts_quantile as panel_ts_quantile,
    ts_rank_pct as panel_ts_rank_pct,
    ts_returns as panel_ts_returns,
    ts_std as panel_ts_std,
    ts_sum as panel_ts_sum,
    ts_var as panel_ts_var,
    ts_wma as panel_ts_wma,
)
from tiger_factors.utils.weighting import (
    normalize_weights,
    score_to_weights,
)

_FACTOR_PREPROCESSING_ALIASES: dict[str, tuple[str, str]] = {
    "demean": ("tiger_factors.factor_preprocessing", "demean"),
    "cs_minmax_neg": ("tiger_factors.factor_preprocessing", "cs_minmax_neg"),
    "cs_minmax_pos": ("tiger_factors.factor_preprocessing", "cs_minmax_pos"),
    "cs_neutralize": ("tiger_factors.factor_preprocessing", "cs_neutralize"),
    "cs_rank": ("tiger_factors.factor_preprocessing", "cs_rank"),
    "cs_winsorize": ("tiger_factors.factor_preprocessing", "cs_winsorize"),
    "cs_winsorize_mad": ("tiger_factors.factor_preprocessing", "cs_winsorize_mad"),
    "cs_zscore": ("tiger_factors.factor_preprocessing", "cs_zscore"),
    "l1_normalize": ("tiger_factors.factor_preprocessing", "l1_normalize"),
    "l2_normalize": ("tiger_factors.factor_preprocessing", "l2_normalize"),
    "minmax_scale": ("tiger_factors.factor_preprocessing", "minmax_scale"),
    "normalize_cross_section": ("tiger_factors.factor_preprocessing", "normalize_cross_section"),
    "neutralize_cross_section": ("tiger_factors.factor_preprocessing", "neutralize_cross_section"),
    "preprocess_cross_section": ("tiger_factors.factor_preprocessing", "preprocess_cross_section"),
    "rank_centered": ("tiger_factors.factor_preprocessing", "rank_centered"),
    "rank_pct": ("tiger_factors.factor_preprocessing", "rank_pct"),
    "robust_zscore": ("tiger_factors.factor_preprocessing", "robust_zscore"),
    "winsorize_cross_section": ("tiger_factors.factor_preprocessing", "winsorize_cross_section"),
    "winsorize_mad": ("tiger_factors.factor_preprocessing", "winsorize_mad"),
    "winsorize_quantile": ("tiger_factors.factor_preprocessing", "winsorize_quantile"),
    "zscore": ("tiger_factors.factor_preprocessing", "zscore"),
}
__all__ = [
    "bucketize_quantiles",
    "combo_a",
    "align_fundamental_point_in_time",
    "panel_cs_rank",
    "panel_cs_regression_residual",
    "panel_cs_skew",
    "panel_cs_standardize",
    "col_minmax_neg",
    "col_minmax_pos",
    "cumulative_return",
    "group_backfill",
    "group_cartesian_product",
    "group_max",
    "group_mean",
    "group_min",
    "group_neutralize",
    "group_rank",
    "group_scale",
    "group_zscore",
    "panel_delay",
    "cs_minmax_neg",
    "cs_minmax_pos",
    "cs_neutralize",
    "cs_rank",
    "cs_winsorize",
    "cs_winsorize_mad",
    "cs_zscore",
    "decay_exponential",
    "decay_linear",
    "demean",
    "diff",
    "drawdown",
    "ewm_mean",
    "ewm_std",
    "expanding_zscore",
    "group_demean",
    "group_dummy_regression_residual",
    "l1_normalize",
    "l2_normalize",
    "lag",
    "log_return",
    "industry_regression_residual",
    "industry_size_regression_residual",
    "make_industry_dummies",
    "make_onehot_by_group",
    "max_drawdown",
    "minmax_scale",
    "normalize_cross_section",
    "neutralize_by_group",
    "neutralize_cross_section",
    "neutralize_industry_size",
    "orthogonalize",
    "pct_change",
    "preprocess_cross_section",
    "rank_centered",
    "rank_pct",
    "panel_rolling_max_drawdown",
    "panel_rolling_sharpe",
    "panel_rolling_volatility",
    "robust_zscore",
    "rolling_beta",
    "rolling_corr",
    "rolling_information_ratio",
    "rolling_kurt",
    "rolling_max",
    "rolling_mean",
    "rolling_median",
    "rolling_min",
    "rolling_rank_pct",
    "rolling_sharpe",
    "rolling_skew",
    "rolling_std",
    "rolling_sum",
    "rolling_zscore",
    "panel_signed_power",
    "panel_ts_av_diff",
    "panel_ts_corr",
    "panel_ts_cov",
    "panel_ts_decay_linear",
    "panel_ts_delta",
    "panel_ts_ema",
    "panel_ts_ir",
    "panel_ts_mean",
    "panel_ts_median",
    "panel_ts_max",
    "panel_ts_min",
    "panel_ts_pctchange",
    "panel_ts_quantile",
    "panel_ts_rank_pct",
    "panel_ts_returns",
    "panel_ts_std",
    "panel_ts_sum",
    "panel_ts_var",
    "panel_ts_wma",
    "ts_arg_max",
    "ts_arg_min",
    "ts_av_diff",
    "ts_backfill",
    "ts_corr",
    "ts_covariance",
    "ts_delay",
    "ts_delta",
    "ts_momentum",
    "ts_max",
    "ts_mean",
    "ts_min",
    "ts_product",
    "ts_quantile",
    "ts_rank",
    "ts_scale",
    "ts_std_dev",
    "ts_sum",
    "ts_ema",
    "ts_pctchange",
    "ts_var",
    "ts_winsorize",
    "ts_winsorize_mad",
    "ts_zscore",
    "ts_wma",
    "volatility",
    "winsorize_cross_section",
    "winsorize_mad",
    "winsorize_quantile",
    "zscore",
    "cs_group_zscore",
    "cross_sectional_zscore",
    "factor_correlation_matrix",
    "greedy_select_by_correlation",
    "blend_factor_panels",
    "normalize_weights",
    "score_to_weights",
]


def __getattr__(name: str):
    target = _FACTOR_PREPROCESSING_ALIASES.get(name)
    if target is not None:
        from importlib import import_module

        module = import_module(target[0])
        value = getattr(module, target[1])
        globals()[name] = value
        return value
    raise AttributeError(f"module 'tiger_factors.utils' has no attribute {name!r}")
